// #include <iostream>

// using namespace std;
// int main(){
//   cout<<"Hello world"<<endl;
//   return 0;
// }

// *******************************Addition of two numbers*********************************

// #include <iostream>
// using namespace std;
// int main(){
// int a = 12;
// int b = 13;
// int sum = a + b;
// cout<<sum<<endl;
// return 0;
// }

// ****************************Taking input from user****************************
#include <iostream>
using namespace std;
int main(){
  char name;
  cout<<"enter your name"<<endl;
  cin>>name;
  cout<<"your name is:"<<name<<endl;
}
