// #include <iostream>

// using namespace std;
// int main(){
//   cout<<"Hello world"<<endl;
//   return 0;
// }

// *******************************Addition of two numbers*********************************

// #include <iostream>
// using namespace std;
// int main(){
// int a = 12;
// int b = 13;
// int sum = a + b;
// cout<<sum<<endl;
// return 0;
// }

// ****************************Taking input from user****************************
// #include <iostream>
// #include <string>
// using namespace std;
// 
// int main(){
//   string name;
//   cout<<"enter your name"<<endl;
//   cin>>name;
//   cout<<"your name is:"<<name<<endl;
// }

// ******************************Conditional statements***************************
// #include <iostream>
// using namespace std;
// int main(){
//   int age;
//   cout<<"enter your age"<<endl;
//   cin>>age;
//   if (age<=18)
//   {
//       cout<<"you cannot drive"<<endl;
//   }
//   else if (age > 18)
//   {
//        cout<<"you can drive"<<endl;
//   }
//   else
//   {
//     cout<<"enter a valid age"<<endl;
//   }
// }